name: "for test"

on: ["push", "pull_request"]

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - name: build
        id: build
        shell: bash
        run: |
          ls ${{ github.workspace }}
          echo "hi"
      - name: run
        id: run
        shell: bash
        run: |
          TESTS=(`echo ${{github.workspace}}/test*.out`)
          for x in "${TESTS[@]}"
          do
            $x
          done

#make -C ${{github.workspace}} test
