name: "for test"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: build
        id: build
        shell: bash
        run: |
          make -C ${{ github.workspace }} test

      - name: run
        id: run
        shell: bash
        run: |
          TESTS=(`echo ${{ github.workspace }}/test*.out`)
          for x in "${TESTS[@]}"
          do
            $x
          done
